### ISSUE TITLE
Order Parts

### ISSUE THREAD

**Issue by Crimson89** [pdxjohnny/flextimus-prime#24]
Order all of the parts for the project for all four group members

**Comment by johnandersen777** [comment]
Depends on #15

**Comment by johnandersen777** [comment]
Let's update the status on this, I remember some discussion in discord

**Comment by fouric** [comment]
I'm an idiot and shipped my parts (LEDs, buttons, headers, USB connectors) to my internship address...in Maryland. Re-ordering now, parts should be here by the end of next week, and I can substitute in some of my own in the meantime.

**Comment by fouric** [comment]
Wow, twice the fool, double the problems; when I re-ordered, I only got six buttons, instead of twelve.

**Comment by fouric** [comment]
Order'd
