### ISSUE TITLE
Development Environment Setup

### ISSUE THREAD

**Issue by johnandersen777** [pdxjohnny/flextimus-prime#29]
What software needs to be installed, whats the host PC setup

**Comment by fouric** [comment]
Use https://github.com/pdxjohnny/flextimus-prime/wiki/fouric's-old-Nucleo-engineering-log for now, I'll create a wiki page soon-ish

**Comment by fouric** [comment]
https://github.com/pdxjohnny/flextimus-prime/wiki/Nucleo-software-quickstart look OK?
